# Generated by Django 5.0.4 on 2024-05-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redundant_expressions', models.TextField(blank=True, null=True)),
                ('inappropriate_terms', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists')),
            ],
        ),
    ]
