# Generated by Django 5.0.4 on 2024-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response',
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
