# Generated by Django 5.0.4 on 2024-05-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0002_remove_interviewanalysis_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewanalysis',
            old_name='question',
            new_name='question_list',
        ),
    ]
