# Generated by Django 5.0.4 on 2024-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanalysis',
            name='intensity_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='intensity_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='pitch_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='pitch_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='pronunciation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='pronunciation_similarity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
