# Generated by Django 5.0.4 on 2024-06-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0003_initial'),
        ('QuestionList', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanalysis',
            name='question_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionList.questionlists'),
        ),
    ]
