# Generated by Django 5.0.4 on 2024-06-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0004_interviewanalysis_intensity_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_1',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_10',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_2',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_3',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_4',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_5',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_6',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_7',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_8',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='response_audio_9',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
