# Generated by Django 5.0.4 on 2024-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAnalyze', '0005_interviewanalysis_response_audio_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewanalysis',
            old_name='intensity_analysis',
            new_name='intensity_graph',
        ),
        migrations.RenameField(
            model_name='interviewanalysis',
            old_name='intensity_message',
            new_name='pitch_graph',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='pitch_analysis',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='pitch_message',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='pronunciation_message',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='pronunciation_similarity',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_1',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_10',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_2',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_3',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_4',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_5',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_6',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_7',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_8',
        ),
        migrations.RemoveField(
            model_name='interviewanalysis',
            name='response_audio_9',
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='intensity_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewanalysis',
            name='pitch_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
